language: ruby
rvm:
- '2.4.2'
sudo: false
cache: bundler
env:
  - RAILS_ENV = test
addons:
  postgresql: '9.5'

before_install:
  - psql -c "CREATE USER exchange WITH PASSWORD 'exchange';" -U postgres

script:
  - bin/setup
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec

deploy:
  - provider: script
      script: bin/generate_docs.sh
      on:
        branch: master
  - provider: pages
      local-dir: gh_pages
      skip-cleanup: true
      github-token: $GH_PAGES_TOKEN  # Set in travis-ci.org dashboard, marked secure
      keep-history: true
      target-branch: gh-pages
      on:
        branch: master