language: ruby
rvm:
- '2.4.2'
sudo: false
cache: bundler
env:
  - RAILS_ENV = test
addons:
  postgresql: '9.5'
  node_js: "5.5"
install: bin/setup
# after_script: bundle exec codeclimate-test-reporter

before_install:
  - cp config/database.yml.travis config/database.yml
  - npm install apidoc -g
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bin/generate_docs.sh
deploy:
  provider: pages
  local-dir: gh_pages
  skip-cleanup: true
  github-token: $GH_PAGES_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master