# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
  oauth_github_id: <%= ENV["GITHUB_OAUTH_ID"] %>
  oauth_github_secret: <%= ENV["GITHUB_OAUTH_SECRET"] %>
  devise_mailer_host: <%= ENV.fetch("EXCHANGE_MAILER_HOST", 'localhost') %>
  devise_mailer_port: <%= ENV.fetch("EXCHANGE_MAILER_PORT", 3000 ) %>
  devise_mailer_address: <%= ENV.fetch("EXCHANGE_EMAIL_SENDER", 'exchange@manageiq.org') %>
  return_configuration:
    items_per_page: 20
development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", 'ee4ee8f5c3c2491b8851eb394e9c81190cfda3cc9890999d3a53825d9cd9a2e7c671a5d9463089b04f6b7f65f068f41baf45ee55e53ce65cbba745987077b69d') %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", '38a770116960477d42b6fc91850cc8b50e23e16f725643ca1f03036f0ce13563260c5ced892332d72cc5bf00781ef7d37bf2e7a936c6dfd9e5c963e4907f48cf') %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
